#!/usr/bin/env Rscript
#############################################################
# tools/build_r_shims.R
#############################################################
#
# Builds minimal `loa` and `AQEval` R packages containing only the handful of
# functions DTEval actually calls, so that R-side parity fixtures can be
# generated on a machine with no Java runtime.
#
# Why this exists
# ---------------
# DTEval reaches AQEval for exactly three calls: findNearLatLon (in
# testTubeAccuracy, deseasonTubeData method 2 and tubeSummaryLatLon) and
# calcDateRangeStat (in testTubeAccuracy). Installing the real AQEval requires
# loa -> OpenStreetMap -> rJava -> a JDK, none of which is present here, and
# none of which those two functions use.
#
# Fidelity
# --------
# The function bodies are **not** hand-transcribed. They are parsed out of the
# genuine upstream sources at a pinned commit/version and re-emitted verbatim
# via deparse(), so the shim cannot drift from the real package by a typo. The
# versions used are recorded in parity/fixtures/_lock.json.
#
# The shims are installed into the project-local .Rlib only, and only when the
# real packages are unavailable -- if a JDK is ever installed and the real
# AQEval alongside it, delete .Rlib and the real package takes over.
#
# Usage:  Rscript tools/build_r_shims.R

invisible(Sys.setlocale("LC_COLLATE", "C"))
options(warn = 1)

root <- getwd()
if (!dir.exists(file.path(root, "parity"))) {
  stop("run tools/build_r_shims.R from the repository root", call. = FALSE)
}
lib <- file.path(root, ".Rlib")
dir.create(lib, recursive = TRUE, showWarnings = FALSE)
.libPaths(c(lib, .libPaths()))

work <- file.path(tempdir(), "dte-shims")
unlink(work, recursive = TRUE)
dir.create(work, recursive = TRUE)

AQEVAL_REPO <- "https://github.com/karlropkins/AQEval.git"
AQEVAL_SHA <- Sys.getenv("DTEVAL_AQEVAL_SHA", "eccaecebdf90e3e65af77f6e876afe12395a0baa")

# ------------------------------------------------------------------ helpers --

#' Pull named functions out of an R source file, verbatim.
#'
#' Parsing and re-deparsing (rather than copying text) guarantees we emit the
#' real definitions and fail loudly if one is missing or renamed upstream.
extract_functions <- function(path, names) {
  env <- new.env()
  exprs <- parse(path)
  for (e in exprs) {
    ok <- tryCatch({ eval(e, envir = env); TRUE }, error = function(err) TRUE)
  }
  missing <- names[!vapply(names, exists, logical(1), envir = env, inherits = FALSE)]
  if (length(missing)) {
    stop("not found in ", basename(path), ": ", paste(missing, collapse = ", "),
         call. = FALSE)
  }
  out <- character(0)
  for (nm in names) {
    fn <- get(nm, envir = env, inherits = FALSE)
    out <- c(out, paste0(nm, " <- ", paste(deparse(fn), collapse = "\n")), "")
  }
  out
}

write_pkg <- function(name, version, title, code, imports = character(0),
                      exports = character(0), provenance = character(0)) {
  dir <- file.path(work, name)
  dir.create(file.path(dir, "R"), recursive = TRUE, showWarnings = FALSE)

  desc <- c(
    paste0("Package: ", name),
    paste0("Version: ", version),
    paste0("Title: ", title),
    "Description: Minimal shim built by DTEval's tools/build_r_shims.R,",
    "    containing only the functions the DTEval parity harness needs. Not a",
    "    substitute for the real package.",
    "Authors@R: person('Karl', 'Ropkins', role = c('aut', 'cre'),",
    "    email = 'k.ropkins@its.leeds.ac.uk')",
    "License: GPL (>= 3)",
    "Encoding: UTF-8"
  )
  if (length(imports)) {
    desc <- c(desc, paste0("Imports: ", paste(imports, collapse = ", ")))
  }
  writeLines(desc, file.path(dir, "DESCRIPTION"))

  ns <- c("exportPattern(\"^[^.]\")", paste0("importFrom(utils, modifyList)"))
  if (length(exports)) ns <- c(paste0("export(", exports, ")"))
  writeLines(ns, file.path(dir, "NAMESPACE"))

  header <- c(
    "###########################################################",
    paste0("# ", name, " -- SHIM, generated by DTEval tools/build_r_shims.R"),
    "#",
    "# Function bodies are parsed verbatim from the upstream source; do not",
    "# edit this file by hand. Provenance:",
    paste0("#   ", provenance),
    "###########################################################",
    ""
  )
  writeLines(c(header, code), file.path(dir, "R", paste0(name, ".R")))

  out <- suppressWarnings(system2(
    "R", c("CMD", "INSTALL", "--no-docs", paste0("--library=", shQuote(lib)), shQuote(dir)),
    stdout = TRUE, stderr = TRUE
  ))
  if (!is.null(attr(out, "status")) && attr(out, "status") != 0) {
    stop("failed to install shim ", name, ":\n", paste(out, collapse = "\n"), call. = FALSE)
  }
  message("installed shim: ", name, " ", version)
}

# --------------------------------------------------------------------- loa --
# AQEval calls loa::listUpdate to merge its argument defaults.

if (requireNamespace("loa", quietly = TRUE) &&
    is.null(attr(utils::packageDescription("loa"), "shim"))) {
  message("real loa present; skipping shim")
  loa_provenance <- paste0("loa ", utils::packageVersion("loa"), " (real package)")
} else {
  cran <- readLines("https://cran.r-project.org/package=loa", warn = FALSE)
  tarball <- regmatches(cran, regexpr("loa_[0-9.]+\\.tar\\.gz", cran))
  tarball <- tarball[nzchar(tarball)][1]
  if (is.na(tarball)) stop("could not determine the current loa version from CRAN")
  src <- file.path(work, tarball)
  utils::download.file(paste0("https://cran.r-project.org/src/contrib/", tarball),
                       src, quiet = TRUE)
  utils::untar(src, exdir = work)
  loa_src <- file.path(work, "loa", "R", "list.handlers.R")
  code <- extract_functions(loa_src, c("listHandler", "listUpdate"))
  loa_provenance <- paste0("CRAN ", tarball, ", R/list.handlers.R")
  write_pkg("loa", "0.0.0.9000", "Shim of loa (listUpdate only)",
            code, exports = c("listUpdate", "listHandler"),
            provenance = loa_provenance)
}

# ------------------------------------------------------------------ AQEval --

aq_dir <- file.path(work, "AQEval-src")
message("cloning AQEval at ", substr(AQEVAL_SHA, 1, 8))
system2("git", c("clone", "--quiet", AQEVAL_REPO, shQuote(aq_dir)))
system2("git", c("-C", shQuote(aq_dir), "checkout", "--quiet", AQEVAL_SHA))

code <- c(
  extract_functions(file.path(aq_dir, "R", "find.near.R"),
                    c("findNearLatLon", "aqe_getXFromData")),
  extract_functions(file.path(aq_dir, "R", "calculate.stats.R"),
                    c("calcDateRangeStat", "aqe_prepFromDate", "aqe_prepToDate"))
)
aq_provenance <- paste0("github.com/karlropkins/AQEval @ ", AQEVAL_SHA,
                        ", R/find.near.R + R/calculate.stats.R")
write_pkg("AQEval", "0.0.0.9000",
          "Shim of AQEval (findNearLatLon, calcDateRangeStat only)",
          code, imports = "loa",
          exports = c("findNearLatLon", "calcDateRangeStat"),
          provenance = aq_provenance)

# ------------------------------------------------------------------ record --
writeLines(
  jsonlite::toJSON(list(
    note = paste("Minimal shims used in place of the real packages;",
                 "see tools/build_r_shims.R"),
    loa = loa_provenance,
    AQEval = aq_provenance,
    aqeval_sha = AQEVAL_SHA
  ), auto_unbox = TRUE, pretty = TRUE),
  file.path(root, "parity", "fixtures", "_shims.json")
)

message("\nshims installed into ", lib)
